#!/bin/bash

read -p "What is the first number? " first
read -p "What is the second number? " second

echo "$first + $second = $((first + second))"
echo "$first - $second = $((first - second))"
echo "$first * $second = $((first * second))"
echo "$first / $second = $((first / second))"
